services:
  # Frontend (Static Site)
  - type: web
    name: pet-store-scheduling-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

  # API (json-server)
  - type: web
    name: pet-store-scheduling-api
    env: node
    buildCommand: npm install
    startCommand: json-server --watch server.json --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
